app = "valortrustfinance"
primary_region = "phx"

[build]
  dockerfile = "Dockerfile"

[env]
  MISE_SETTINGS_PYTHON_COMPILE = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.ports]]
    handlers = ["http"]
    port = 80

  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443
